global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring_actuator'
    metrics_path: '/apigw/actuator/prometheus'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['molatest.bulvia.com']