global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring_actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['a84a-213-14-146-110.ngrok-free.app']